[tool.poetry]
name = "palmer_streamlit"
version = "0.1.0"
description = "A Streamlit application for the Palmer Lab to access the database."
authors = ["Elaine Keung <ekeung@health.ucsd.edu>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12.dev0"
pandas = "^2.2.3"
matplotlib = "^3.10.3"
dotenv = "^0.9.9"
streamlit = "1.31.0"
pyarrow = "^14.0.2"
plotly = "^6.1.2"
panel = "^1.7.1"
holoviews = "^1.20.2"
streamlit-cognito-auth = {git = "https://github.com/elainekeung/streamlit-cognito-auth.git"}
st-pages = "0.4.5"
sqlalchemy = "^2.0.41"
stqdm = "^0.0.5"
psycopg2-binary = "^2.9.10"
ipython = "^9.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
