[[pages]]
path = "home.py"
name = "Home"
icon = ""
is_section = false

[[pages]]
name = "Palmer Lab Access"
is_section = true
icon = ""

[[pages]]
path = "pages/Summary.py"
name = "Database Summary"
icon = ""

[[pages]]
path = "pages/Sample Tracking.py"
name = "Sample Tracking"
icon = ""

[[pages]]
path = "pages/dictionary.py"
name = "Data Dictionary"
icon = ""

[[pages]]
path = "pages/metadata.py"
name = "Genotyping Metadata"
icon = ""

[[pages]]
name = "Public"
is_section = true
icon = ""

[[pages]]
path = "pages/genotype.py"
name = "Genotyping Reports"
icon = ""
