[[pages]]
path = "home.py"
name = "Home"
icon = ""
is_section = false

[[pages]]
name = "Palmer Lab Access"
is_section = true
icon = ""

[[pages]]
path = "pages/Summary.py"
name = "Database Summary"
icon = ""

[[pages]]
path = "pages/Sample Tracking.py"
name = "Sample Tracking"
icon = ""

[[pages]]
path = "pages/dictionary.py"
name = "Data Dictionary"
icon = ""

[[pages]]
path = "pages/metadata.py"
name = "Genotyping Metadata"
icon = ""

[[pages]]
path = "pages/rattaca.py"
name = "HS West Records"
icon = "" 

[[pages]]
name = "Tools"
is_section = true
icon = ""

[[pages]]
path = "pages/medpc.py"
name = "MedPC Extractor"
icon = ""

[[pages]]
path = "pages/locuszoom.py"
name = "Regional Association Tools"
icon = ""

[[pages]]
path = "pages/report.py"
name = "GWAS Reports"
icon = ""

[[pages]]
path = "pages/rfid_metadata.py"
name = "Rat Metadata"
icon = ""

[[pages]]
path = "pages/tables.py"
name = "Database Records"
icon = ""

[[pages]]
name = "Public"
is_section = true
icon = ""

[[pages]]
path = "pages/genotype.py"
name = "Genotyping Reports"
icon = ""
