[connections.palmerdb]
dialect = "postgresql"
username = "postgres"
password = "palmerlab-amapostgres"
host = "palmerlab-main-database-c2021-08-02.c6sgfwysomht.us-west-2.rds.amazonaws.com"
database = "PalmerLab_Datasets"
port = "5432"


